spring:
  profiles:
    active: local
  application:
    name: gp-file

# 【dev环境】
---
spring:
  config:
    activate:
      on-profile: dev


server:
  port: 8102

# 【local环境】
---
spring:
  config:
    activate:
      on-profile: local
# mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.14:3306/gp_file
    username: root
    password: 3186255

server:
  port: 8102


