spring:
  profiles:
    active: local
  application:
    name: gp-auth-service



# [local环境]
---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        namespace: 5e09156e-dc92-4641-8aba-bc14328befa8
        group: gp-project


server:
  port: 8101
gp:
  auth:
    resource:
      exclude-path:
        - "/account/login"
    jwt:
      expire: 172800 # 2天
      secret: "`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./"
