spring:
  profiles:
    active: local
  application:
    name: gp-common



# 【dev环境】
---
spring:
  config:
    activate:
      on-profile: dev




# 【local环境】
---
spring:
  config:
    activate:
      on-profile: local


