spring:
  profiles:
    active: local
  application:
    name: gp-user-service

# 【dev环境】
---
spring:
  config:
    activate:
      on-profile: dev


server:
  port: 8103

# 【local环境】
---
spring:
  config:
    activate:
      on-profile: local
  # mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gp_user
    username: root
    password: 3186255
  # nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        group: gp-project
        namespace: 5e09156e-dc92-4641-8aba-bc14328befa8


logging:
  level:
    com.gp_01.user: debug



server:
  port: 8103
gp:
  auth:
    resource:
      enable: true
      exclude-path:
        - "/user/create"
      include-path:
        - "/user/**"