spring:
  profiles:
    active: local
  application:
    name: gp-user-service
  config:
    import:
    - "optional:nacos:shared-mybatis-plus-local.yaml?group=gp-project&namespace=5e09156e-dc92-4641-8aba-bc14328befa8&refreshEnabled=true"
    - "optional:nacos:gp-user-service-local.yaml?group=gp-project&namespace=5e09156e-dc92-4641-8aba-bc14328befa8&refreshEnabled=true"

  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        group: gp-project
        namespace: 5e09156e-dc92-4641-8aba-bc14328befa8
      config:
        group: gp-project
        namespace: 5e09156e-dc92-4641-8aba-bc14328befa8
        file-extension: yaml

server:
  port: 8103



