spring:
  profiles:
    active: local
  application:
    name: gp-file-service

# 【dev环境】
---
spring:
  config:
    activate:
      on-profile: dev


server:
  port: 8102

# 【local环境】
---
spring:
  servlet:
    multipart:
      # 设置最大上传文件大小
      max-file-size: 10GB
      max-request-size: 15GB
  config:
    activate:
      on-profile: local
# mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gp_file
    username: root
    password: 3186255
  # nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        group: gp-project
        namespace: 5e09156e-dc92-4641-8aba-bc14328befa8
  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: gp_01
    username: admin
    password: 3186255

  # redis
  data:
    redis:
      host: localhost
      database: 0
      port: 6379

logging:
  level:
    com.gp_01.file: debug

gp:
  file-service:
    recycle-save-day: 10
    chunk-upload-threshold: 100MB
    chunk-strategy-map:
      0MB: 10MB
      1GB: 50MB
      10GB: 100MB
      50GB: 200MB
  minio:
    url: http://localhost:9000
    access-key: admin
    secret-key: Syq3186255
    bucket-name: local
    temp-signed-url-expire-minute: 10
    temp-bucket-name: temp
    avatar-bucket-name: local-avatar
  thumbnails:
    width: 100
  auth:
    resource:
      enable: true
      include-path:
        - "/user-file/**"
        - "/file-base/**"
      exclude-path:
        - "/file-base/test"
        - "/user-file/test"
server:
  port: 8102

